name: Test Workflow

on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ github_actions ]
  workflow_dispatch:

jobs:

  # Generates Matrix
  generate-matrix:
    name:

    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Install required libs
      - name: Install CMocka
        run: sudo apt-get install libcmocka0 libcmocka-dev
      # Create all test files
      - name: Create Test Files
        run: cd firmware/tests/devices && make all
      # Generates JSON file with test program
      - name: Create JSON file
        run: python3 .github/workflows/deployJSON.py --generate firmware/tests/devices/
      # Echo the JSON file
      - name: Resulting JSON file for matrix generation
        run: echo "$(cat .github/workflows/test-list.json)"
      # Set the matrix output from the JSON (manipulated to remove spaces and replace \n -> %0A, " -> \")
      - id: set-matrix
        name: Set matrix output from the JSON file
        run: echo "::set-output name=matrix::$( echo "$(cat .github/workflows/test-list.json)" | sed ':a;N;$!ba;s/\n/%0A/g' )"

  # Job for executing all test files
  run-tests:
    name: run-tests
    needs: generate-matrix
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}


    env:
      TEST_NAME: ${{ matrix.name }}
      TEST_PATH: ${{ matrix.path }}

    steps:
      - uses: actions/checkout@v2
      - name: Signal run test
        run: echo  Running $TEST_NAME
      - name: LS
        run: ls -la
      - name: cd firmware
        run: cd firmware/tests/devices && ls
